
import Footer from "./components/Common/Footer";
import Navbar from "./components/Common/Navbar";
import "./globals.css";
import CustomCursor from "./Reusable/CustomCursor";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <CustomCursor/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
